# Generated by Django 3.0.6 on 2020-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='transcType',
            field=models.CharField(choices=[('income', 'INCOME'), ('expenditure', 'EXPENDITURE')], max_length=20),
        ),
    ]
