# Generated by Django 3.0.6 on 2020-08-07 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200807_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='note_received', to='bank.Customer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_sent', to='bank.Customer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_user', to='bank.Customer'),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ManyToManyField(related_name='customer', to='bank.Customer'),
        ),
        migrations.AlterField(
            model_name='history',
            name='transcType',
            field=models.CharField(choices=[('Income', 'INCOME'), ('Expenditure', 'EXPENDITURE')], max_length=20),
        ),
    ]
