# Generated by Django 3.0.6 on 2020-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_customer_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.CharField(default='Savings', max_length=200),
        ),
    ]
