# Generated by Django 3.0.6 on 2020-08-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20200808_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='fullName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
