# Generated by Django 3.0.6 on 2020-08-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20200809_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
