# Generated by Django 3.0.6 on 2020-08-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20200809_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='tel',
            new_name='whatsappNum',
        ),
    ]
