# Generated by Django 3.0.6 on 2020-08-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20200809_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
