# Generated by Django 3.0.6 on 2020-08-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20200812_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='transactionId',
            field=models.IntegerField(default=0),
        ),
    ]
