# Generated by Django 3.0.6 on 2020-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_auto_20200818_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsummary',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
