# Generated by Django 3.0.6 on 2020-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_auto_20200818_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsummary',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
