# Generated by Django 3.0.6 on 2020-08-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20200821_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
