# Generated by Django 3.0.6 on 2020-08-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
